# Generated by Django 3.1.6 on 2021-02-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USerInfo',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('userpwd', models.CharField(max_length=20)),
            ],
        ),
    ]
